### ISSUE TITLE
Does this also open current file in AppCode?

### ISSUE THREAD

**Issue by dxclancy** [orta/OROpenInAppCode#8]

**Comment by orta** [comment]
Yep, should do

**Comment by dxclancy** [comment]
Sorry to bother you.  It doesn't seem to be working for me.  Included is a screenshot after relaunching Xcode that shows the plugin installed via alcatraz and the file menu but "no open in appcode" item. 

I'm running Xcode 6.4.2.  Perhaps that is the problem?

![openinappcode](https://cloud.githubusercontent.com/assets/1066271/10356501/c0167c22-6d2c-11e5-80c6-7b763fbfe65e.jpg)
