### ISSUE TITLE
No app code menu in Xcode after install and restart

### ISSUE THREAD

**Issue by dxclancy** [orta/OROpenInAppCode#9]
Sorry to bother you.  It doesn't seem to be working for me.  Included is a screenshot after relaunching Xcode that shows the plugin installed via alcatraz and the file menu but "no open in appcode" item. 

I'm running Xcode 6.4.2.  Perhaps that is the problem?

![openinappcode](https://cloud.githubusercontent.com/assets/1066271/10356501/c0167c22-6d2c-11e5-80c6-7b763fbfe65e.jpg)

**Comment by dxclancy** [comment]
Also doesn't seem to be working for me in Xcode 7. Any suggestions?

**Comment by orta** [comment]
It probably needs the UUID for the specific version of Xcode adding, feel free to clone it locally and check the plist :+1:

**Comment by dxclancy** [comment]
I tried to follow the advice here:
https://github.com/supermarin/Alcatraz/issues/73
but after adding the UUID, it still didn't seem to work.

Then I uninstalled and reinstalled, and it worked.  I had done this many times before messing with the plist to no avail.

thanks.
